#!/bin/sh

set -eo pipefail

JS_FILES=$(git diff --cached --name-only --diff-filter=ACMR "lib/**.js" | sed 's| |\\ |g')
if [ -n "$JS_FILES" ]; then
  npm run format
  echo "$JS_FILES" | xargs git add
fi
